server {
	listen 80 default_server;
	listen 443 ssl;
	http2 on;

	server_name _;
	
	ssl_certificate /etc/nginx/server.crt.pem;
	ssl_certificate_key /etc/nginx/server.key.pem;
	ssl_protocols TLSv1.3 TLSv1.2 TLSv1.1 TLSv1;
	ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_buffer_size 4k;
	ssl_stapling off;
	ssl_stapling_verify off;
	ssl_session_tickets off;
	ssl_session_cache off;
	ssl_conf_command NumTickets 0;
	keepalive_timeout 0;


	# autoindex off;
	gzip off;
	
	root /var/www/html;
	index index.html;

	if ($scheme != "https") { return 302 "https://$host$request_uri"; }

	location / {
		default_type application/json;
    return 200 "{\n  \"ua\": \"$http_user_agent\",\n  \"ip\": \"$remote_addr\",\n  \"ja3\":\"$http_ssl_ja3\",\n  \"ja3_hash\":\"$http_ssl_ja3_hash\",\n  \"ja4\":\"$http_ssl_ja4\",\n  \"akamai\":\"$http2_fingerprint\"\n}";
		# try_files $uri $uri/ =404;
	}

}
